app:
  name: hostsent-backend
  env: development
  host: 0.0.0.0
  port: 8081
  read_timeout: 10
  write_timeout: 10

auth:
  bearer_prefix: Bearer
  jwt_secret: hostsent-dev-secret
  jwt_issuer: hostsent-backend
  jwt_expire_hours: 24

database:
  host: 127.0.0.1
  port: 5432
  user: hostsent
  password: hostsent
  name: hostsent
  sslmode: disable
